autoclave/urls.py
from django.urls import path
from .views import AutoclaveTemperatureListView, AutoclaveTemperatureCreateView, sync_data_view, temperature_delete, temperature_edit, update_verification, AutoclaveCreateView

app_name = 'autoclave'

urlpatterns = [
    path('', AutoclaveTemperatureListView.as_view(), name='temperature_list'),  # Listado de temperaturas
    path('add/', AutoclaveTemperatureCreateView.as_view(), name='temperature_add'),  # Formulario para agregar temperatura
    path('edit/<int:id_temp_autoclave>/', temperature_edit, name='temperature_edit'),  # Modificar temperatura
    path('delete/<int:id_temp_autoclave>/', temperature_delete, name='temperature_delete'),  # Eliminar temperatura
    path('sync/', sync_data_view, name='sync_data'),
    path('update_verification/', update_verification, name='update_verification'),
    path('add_autoclave/', AutoclaveCreateView.as_view(), name='add_autoclave'),  # Formulario para agregar autoclave
    
]

core/urls.py
from django.urls import path
from .views import HomePageView
from .views import sync_databases_view

app_name = 'core'

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),   
    path('sync-databases/', sync_databases_view, name='sync_databases'), 

    
    
]

procesos/urls.py
# procesos/urls.py
from django.urls import path
from .views import ProcesosListView, ProcesosCreateView, ProcesosUpdateView, activar_desactivar_proceso

app_name = 'procesos'

urlpatterns = [
    path('', ProcesosListView.as_view(), name='procesos_list'),
    path('add/', ProcesosCreateView.as_view(), name='procesos_add'),
    path('<int:pk>/edit/', ProcesosUpdateView.as_view(), name='procesos_edit'),
    path('<int:pk>/activar_desactivar/', activar_desactivar_proceso, name='procesos_activar_desactivar'),
]

production/urls.py
from django.urls import path
from . import views
app_name = 'production'  # Asegúrate de tener esto si usas un namespace

urlpatterns = [
    path('registrar_paro/', views.registrar_paro, name='registrar_paro'),
    path('production/', views.production, name='production'),
    path('registro/', views.registro, name='registro'),
    path('modificar_paro/<int:paro_id>/', views.modificar_paro, name='modificar_paro'),
    path('eliminar_paro/<int:paro_id>/', views.eliminar_paro, name='eliminar_paro'),
    path('registro_maquinaria/', views.registro_maquinaria, name='registro_maquinaria'),
    path('registro_proceso/', views.registro_proceso, name='registro_proceso'),
    path('registro_concepto/', views.registro_concepto, name='registro_concepto'),  # Nueva ruta para registrar concepto
    path('modificar_proceso/<int:proceso_id>/', views.modificar_proceso, name='modificar_proceso'),
    path('modificar_maquinaria/<int:maquinaria_id>/', views.modificar_maquinaria, name='modificar_maquinaria'),
    path('modificar_concepto/<int:concepto_id>/', views.modificar_concepto, name='modificar_concepto'),  # Nueva ruta para modificar concepto
    path('cambiar/estado/proceso/<int:id_proceso>/', views.cambiar_estado_proceso, name='cambiar_estado_proceso'),  # Cambiar estado de proceso
    path('cambiar/estado/maquinaria/<int:id_maquinaria>/', views.cambiar_estado_maquinaria, name='cambiar_estado_maquinaria'),  # Cambiar estado de maquinaria
    path('sync/', views.sync_data_view, name='sync_data_view'),  # Nueva ruta
    path('syncProc/', views.sync_procesos_view, name='sync_procesos'),  # Nueva ruta
    path('syncMaq/', views.sync_maquinaria_view, name='sync_maquinaria'),  # Nueva ruta 
    path('syncConceptos/', views.sync_conceptos_view, name='sync_conceptos'),  # Nueva ruta para sincronizar conceptos
    path('modificar_paro_mant/<int:paro_id>/', views.modificar_paro_mant, name='modificar_paro_mant'),
    path('filtrar_paros/', views.filtrar_paros, name='filtrar_paros'),
    path('get_productos/', views.get_productos, name='get_productos'),
]

proyecto_Moo/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('procesos/', include('procesos.urls')),
    path('horas_procesos/', include('horas_procesos.urls', namespace='horas_procesos')),
    path('', include('core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
    path('', HomePageView.as_view(), name="home"),
    path('temperature/', include('temperature.urls')),  # Incluir las rutas de temperature
    path('production/', include('production.urls')),
    path('esterilizadores/', include('esterilizadores.urls')),
   
    path('autoclave/', include("autoclave.urls")),
]

usuarios/urls.py
# usuarios/urls.py
from django.urls import path
from .views import UserListView, UserCreateView, UserUpdateView, UserDeleteView

app_name = 'usuarios'

urlpatterns = [
    path('users/', UserListView.as_view(), name='user_list'),
    path('users/add/', UserCreateView.as_view(), name='user_add'),
    path('users/<int:pk>/edit/', UserUpdateView.as_view(), name='user_edit'),
    path('users/<int:pk>/delete/', UserDeleteView.as_view(), name='user_delete'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
import subprocess
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

@method_decorator(login_required, name='dispatch')
class HomePageView(TemplateView):
    template_name = "core/home.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Sana Premium Foods"
        context['user_groups'] = self.request.user.groups.values_list('name', flat=True)
        return context

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.get_context_data())

class SamplePageView(TemplateView):
    template_name = "core/sample.html"

@csrf_exempt
def sync_databases_view(request):
    if request.method == 'POST':
        try:
            # Ejecutar el script de sincronización de bases de datos
            subprocess.run(['python', 'core/sync_db.py'], check=True)
            
            # Ejecutar el script de sincronización de checadas
            subprocess.run(['python', 'core/sync_checada.py'], check=True)
            
            return JsonResponse({'status': 'success', 'message': 'Sincronización completada con éxito.'})
        except subprocess.CalledProcessError as e:
            return JsonResponse({'status': 'error', 'message': str(e)})
    return JsonResponse({'status': 'error', 'message': 'Método no permitido.'})

core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block title %}Sana Premium Foods{% endblock %}</title>
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico' %}" />
    <link href="{% static 'core/css/styles.css' %}" rel="stylesheet"/>
    {% load i18n %}
    <!-- Fuentes -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,700,700i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Estilos adicionales -->
    <link href="{% static 'core/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'core/css/main.css' %}" rel="stylesheet">
</head>
<body id="page-top">
    <!-- Navegación -->
    <nav class="navbar navbar-expand-lg fixed-top" id="mainNav" style="border-bottom: 2px solid #ccc;"> 
        <div class="container px-4">
            <a class="navbar-brand" href="{% url 'core:home' %}">
                <img src="{% static 'core/assets/logosana.jpg' %}" alt="Sana Premium Foods Logo" height="40">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav me-auto ms-3">
                    {% if request.user.is_authenticated %}
                        {% if 'Produccion' in user_groups or 'IT' in user_groups %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Producción
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="{% url 'production:production' %}">Registros de Paros de Producción</a></li>
                                    <li><a class="dropdown-item" href="{% url 'horas_procesos:gestion_horas_procesos' %}">Horas Procesos</a></li>
                                    <li><a class="dropdown-item" href="{% url 'horas_procesos:empleados_por_departamento' %}">Lista De Asistencia</a></li>
                                    {% if request.user.is_staff %}
                                    <li><a class="dropdown-item" href="{% url 'production:registro' %}">Catalogo De Procesos</a></li>
                                    {% endif %}
                                </ul>
                            </li>
                        {% endif %}
                        {% if 'Calidad' in user_groups or 'IT' in user_groups %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Calidad
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="{% url 'autoclave:temperature_list' %}">Temperaturas Autoclave</a></li>
                                    <li><a class="dropdown-item" href="{% url 'esterilizadores:tempester' %}">Temperaturas Esterilizador</a></li> 
                                    <li><a class="dropdown-item" href="{% url 'temperature:temperature' %}">Temperaturas Generales</a></li>
                                </ul>
                            </li>
                        {% endif %}
                    {% endif %}
                    {% if request.user.is_superuser %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'usuarios:user_list' %}">Usuarios</a></li>
                    {% endif %}
                    {% if request.user.is_staff %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'procesos:procesos_list' %}">Procesos</a></li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav ms-auto" id="navbar-right"> 
                    {% if not request.user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Acceder</a></li>
                    {% else %}
                    <li class="nav-item">
                        <form id="logout-form" method="post" action="{% url 'logout' %}">
                            {% csrf_token %}
                            <button type="submit" class="nav-link btn btn-link" style="padding: 0;">{% trans "Log out" %}</button>
                        </form>
                    </li>
                    {% endif %}
                </ul>
                {% block navbar_extra %}{% endblock %}
            </div>
        </div>
    </nav>
    
    {% block content %}{% endblock %}

    <!-- Bootstrap y js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Inicio{% endblock %}
{% block navbar_extra %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const navbarRight = document.getElementById('navbar-right');
        if (window.location.pathname === '/') {
            const syncButton = document.createElement('li');
            syncButton.className = 'nav-item';
            syncButton.innerHTML = `
                <form id="sync-form" method="post" action="{% url 'core:sync_databases' %}">
                    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
                    <button type="submit" class="nav-link btn btn-link" style="padding: 0;">Sincronizar Bases de Datos</button>
                </form>
            `;
            navbarRight.insertBefore(syncButton, navbarRight.firstChild);

            document.getElementById('sync-form').addEventListener('submit', function(event) {
                event.preventDefault();  // Evitar el comportamiento predeterminado del formulario
                fetch("{% url 'core:sync_databases' %}", {
                    method: 'POST',
                    headers: {
                        'X-CSRFToken': '{{ csrf_token }}',
                        'Content-Type': 'application/json'
                    }
                })
                .then(response => response.json())
                .then(data => {
                    if (data.status === 'success') {
                        alert('Sincronización completada con éxito.');
                    } else {
                        alert('Error en la sincronización: ' + data.message);
                    }
                })
                .catch(error => {
                    alert('Error en la sincronización: ' + error.message);
                });
            });
        }
    });
</script>
<style>
    .nav-item {
        margin-right: 15px; /* Ajusta este valor según sea necesario */
      }
</style>
{% endblock %}
{% block content %}
<header class="text-white" style="background-image: url('{% static 'core/assets/fondoHome.png' %}'); background-repeat: repeat; background-position: center;">
    <div class="container px-4 text-center">
        <h1 class="fw-bolder">SANA Realtime WebApp</h1>
        <p class="lead">Aplicación web oficial para uso del personal de calidad.</p>
    </div>
</header>

<section id="about">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <h2>Acerca de la app</h2>
                <p class="lead">
                    Aplicación web diseñada para automatizar procesos de captura de información en procesos. Su funcionamiento se basa en la integración de tecnologías avanzadas que permiten recopilar, procesar y analizar datos en tiempo real.
                </p>
                <p class="lead">
                    Los operarios pueden ingresar datos fácilmente a través de una interfaz intuitiva (tablet, laptop o pc), lo que reduce errores y optimiza el flujo de trabajo. La aplicación genera reportes automáticos, proporciona visibilidad instantánea del estado de los procesos y facilita la toma de decisiones informadas. Con Sana Realtime WebApp se puede mejorar su eficiencia operativa y reducir costos, transformando la manera en que gestionan la información.
                </p>
            </div>
        </div>
    </div>
</section>
<footer class="bg-dark text-white py-1">
    <div class="container text-center">
        <div class="mt-4">
            <p>&copy; {{ current_year }} Sana Premium Foods. Todos los derechos reservados.</p>
        </div>
    </div>
</footer>
{% endblock %}